channels:
- conda-forge
- default
dependencies:
- gcc_linux-64
- gfortran_linux-64
- cmake
- make
- m4
- git
- pip
- mingw-w64-x86_64-python-ipykernel
- pip:
  - numpy
  - GitPython 
  - pyvistaqt
  - itkwidgets
  - jupyter
  - sphinx
  - sphinx-gallery
  - sphinx_bootstrap_theme
  - numpydoc

