C
C**************************  OPENIO ************************************
C
C  open the input and output files
C
C***********************************************************************
C
      SUBROUTINE OPENIO
C
      IMPLICIT NONE
      CHARACTER*1  CHAR
      CHARACTER*150 DIR
      CHARACTER*150 FNI1,  FNI2, FNI3, FNI4,  FNI5, FNI6
      CHARACTER*150 FNI7,  FNI8, FNI9, FNI10, FNI11
      CHARACTER*150 FNI16, FNI17, FNI18, FNI20
      CHARACTER*150 FNI21, FNI22, FNI23, FNI25
      CHARACTER*150 FNI26, FNI27, FNI28, FNI29, FNI30
      CHARACTER*150 FNI31, FNI32, FNI33, FNI34, FNI35
      CHARACTER*150 FNI36, FNI37, FNI38, FNI39
      CHARACTER*150 FNI50, FNI51, FNI60
      CHARACTER*150 FNI61, FNI62, FNI63, FNI64            
      CHARACTER*150 FNTERM
      CHARACTER*150 FNO1, FNO2, FNO3, FNO4, FNO5, FNO6
      CHARACTER*150 FNO7, FNO8, FNO9, FNO10,FNO11,FNO12
      CHARACTER*150 FNO13,FNO14,FNO15,FNO16,FNO17,FNO18
      CHARACTER*150 FNO19,FNO20,FNO30,FNO31,FNO32,FNO36
      CHARACTER*150 FNO40,FNO41,FNO42,FNO43,FNO44
      CHARACTER*150 FNO50,FNO51,FNO57,FNO80,FNO81
      CHARACTER*150 FNOPT
      INTEGER      I,NCHAR
      INCLUDE     'IOUNITS.H'
C
C  open the I/O files
C
      OPEN(IFN,FILE='cathy.fnames',STATUS='UNKNOWN')
      READ(IFN,*) DIR
      CHAR = '.'
      I = 1
      DO WHILE (CHAR.NE.' ')
         CHAR = DIR(I:I)
         NCHAR = I
         I = I + 1
      END DO
      NCHAR = NCHAR - 1
      READ(IFN,*) FNI1
      READ(IFN,*) FNI2
      READ(IFN,*) FNI3
      READ(IFN,*) FNI4
      READ(IFN,*) FNI5
      READ(IFN,*) FNI6
      READ(IFN,*) FNI7
      READ(IFN,*) FNI8
      READ(IFN,*) FNI9
      READ(IFN,*) FNI10
      READ(IFN,*) FNI11
      READ(IFN,*) FNI16
      READ(IFN,*) FNI17
      READ(IFN,*) FNI18
      READ(IFN,*) FNI20
      READ(IFN,*) FNI21
      READ(IFN,*) FNI22
      READ(IFN,*) FNI23
      READ(IFN,*) FNI25
      READ(IFN,*) FNI26
      READ(IFN,*) FNI27
      READ(IFN,*) FNI28
      READ(IFN,*) FNI29
      READ(IFN,*) FNI30
      READ(IFN,*) FNI31
      READ(IFN,*) FNI32
      READ(IFN,*) FNI33
      READ(IFN,*) FNI34
      READ(IFN,*) FNI35
      READ(IFN,*) FNI36
      READ(IFN,*) FNI37
      READ(IFN,*) FNI38
      READ(IFN,*) FNI39
      READ(IFN,*) FNI50
      READ(IFN,*) FNI51
      READ(IFN,*) FNI60
      READ(IFN,*) FNI61
      READ(IFN,*) FNI62
      READ(IFN,*) FNI63
      READ(IFN,*) FNI64
      READ(IFN,*) FNO1
      READ(IFN,*) FNO2
      READ(IFN,*) FNO3
      READ(IFN,*) FNO4
      READ(IFN,*) FNO5
      READ(IFN,*) FNO6
      READ(IFN,*) FNO7
      READ(IFN,*) FNO8
      READ(IFN,*) FNO9
      READ(IFN,*) FNO10
      READ(IFN,*) FNO11
      READ(IFN,*) FNO12
      READ(IFN,*) FNO13
      READ(IFN,*) FNO14
      READ(IFN,*) FNO15
      READ(IFN,*) FNO16
      READ(IFN,*) FNO17
      READ(IFN,*) FNO18
      READ(IFN,*) FNO19
      READ(IFN,*) FNO20
      READ(IFN,*) FNO30
      READ(IFN,*) FNO31
      READ(IFN,*) FNO32
      READ(IFN,*) FNO36
      READ(IFN,*) FNO40
      READ(IFN,*) FNO41
      READ(IFN,*) FNO42
      READ(IFN,*) FNO43
      READ(IFN,*) FNO44
      READ(IFN,*) FNO50
      READ(IFN,*) FNO51
      READ(IFN,*) FNO57
      READ(IFN,*) FNO80
      READ(IFN,*) FNO81
      READ(IFN,*) FNOPT
      FNI1=DIR(1:NCHAR)//'/'//FNI1
      FNI2=DIR(1:NCHAR)//'/'//FNI2
      FNI3=DIR(1:NCHAR)//'/'//FNI3
      FNI4=DIR(1:NCHAR)//'/'//FNI4
      FNI5=DIR(1:NCHAR)//'/'//FNI5
      FNI6=DIR(1:NCHAR)//'/'//FNI6
      FNI7=DIR(1:NCHAR)//'/'//FNI7
      FNI8=DIR(1:NCHAR)//'/'//FNI8
      FNI9=DIR(1:NCHAR)//'/'//FNI9
      FNI10=DIR(1:NCHAR)//'/'//FNI10
      FNI11=DIR(1:NCHAR)//'/'//FNI11
      FNI16=DIR(1:NCHAR)//'/'//FNI16
      FNI17=DIR(1:NCHAR)//'/'//FNI17
      FNI18=DIR(1:NCHAR)//'/'//FNI18
      FNI20=DIR(1:NCHAR)//'/'//FNI20
      FNI21=DIR(1:NCHAR)//'/'//FNI21
      FNI22=DIR(1:NCHAR)//'/'//FNI22
      FNI23=DIR(1:NCHAR)//'/'//FNI23
      FNI25=DIR(1:NCHAR)//'/'//FNI25
      FNI26=DIR(1:NCHAR)//'/'//FNI26
      FNI27=DIR(1:NCHAR)//'/'//FNI27
      FNI28=DIR(1:NCHAR)//'/'//FNI28
      FNI29=DIR(1:NCHAR)//'/'//FNI29
      FNI30=DIR(1:NCHAR)//'/'//FNI30
      FNI31=DIR(1:NCHAR)//'/'//FNI31
      FNI32=DIR(1:NCHAR)//'/'//FNI32
      FNI33=DIR(1:NCHAR)//'/'//FNI33
      FNI34=DIR(1:NCHAR)//'/'//FNI34
      FNI35=DIR(1:NCHAR)//'/'//FNI35
      FNI36=DIR(1:NCHAR)//'/'//FNI36
      FNI37=DIR(1:NCHAR)//'/'//FNI37
      FNI38=DIR(1:NCHAR)//'/'//FNI38
      FNI39=DIR(1:NCHAR)//'/'//FNI39
      FNI50=DIR(1:NCHAR)//'/'//FNI50
      FNI51=DIR(1:NCHAR)//'/'//FNI51
      FNI60=DIR(1:NCHAR)//'/'//FNI60
      FNI61=DIR(1:NCHAR)//'/'//FNI61
      FNI62=DIR(1:NCHAR)//'/'//FNI62
      FNI63=DIR(1:NCHAR)//'/'//FNI63
      FNI64=DIR(1:NCHAR)//'/'//FNI64
      IF(FNO1 .NE. '/dev/null') FNO1=DIR(1:NCHAR)//'/'//FNO1
      IF(FNO2 .NE. '/dev/null') FNO2=DIR(1:NCHAR)//'/'//FNO2
      IF(FNO3 .NE. '/dev/null') FNO3=DIR(1:NCHAR)//'/'//FNO3
      IF(FNO4 .NE. '/dev/null') FNO4=DIR(1:NCHAR)//'/'//FNO4
      IF(FNO5 .NE. '/dev/null') FNO5=DIR(1:NCHAR)//'/'//FNO5
      IF(FNO6 .NE. '/dev/null') FNO6=DIR(1:NCHAR)//'/'//FNO6
      IF(FNO7 .NE. '/dev/null') FNO7=DIR(1:NCHAR)//'/'//FNO7
      IF(FNO8 .NE. '/dev/null') FNO8=DIR(1:NCHAR)//'/'//FNO8
      IF(FNO9 .NE. '/dev/null') FNO9=DIR(1:NCHAR)//'/'//FNO9
      IF(FNO10.NE. '/dev/null') FNO10=DIR(1:NCHAR)//'/'//FNO10
      IF(FNO11.NE. '/dev/null') FNO11=DIR(1:NCHAR)//'/'//FNO11
      IF(FNO12.NE. '/dev/null') FNO12=DIR(1:NCHAR)//'/'//FNO12
      IF(FNO13.NE. '/dev/null') FNO13=DIR(1:NCHAR)//'/'//FNO13
      IF(FNO14.NE. '/dev/null') FNO14=DIR(1:NCHAR)//'/'//FNO14
      IF(FNO15.NE. '/dev/null') FNO15=DIR(1:NCHAR)//'/'//FNO15
      IF(FNO16.NE. '/dev/null') FNO16=DIR(1:NCHAR)//'/'//FNO16
      IF(FNO17.NE. '/dev/null') FNO17=DIR(1:NCHAR)//'/'//FNO17
      IF(FNO18.NE. '/dev/null') FNO18=DIR(1:NCHAR)//'/'//FNO18
      IF(FNO19.NE. '/dev/null') FNO19=DIR(1:NCHAR)//'/'//FNO19
      IF(FNO10.NE. '/dev/null') FNO20=DIR(1:NCHAR)//'/'//FNO20
      IF(FNO30.NE. '/dev/null') FNO30=DIR(1:NCHAR)//'/'//FNO30
      IF(FNO31.NE. '/dev/null') FNO31=DIR(1:NCHAR)//'/'//FNO31
      IF(FNO32.NE. '/dev/null') FNO32=DIR(1:NCHAR)//'/'//FNO32
      IF(FNO36.NE. '/dev/null') FNO36=DIR(1:NCHAR)//'/'//FNO36
      IF(FNO40.NE. '/dev/null') FNO40=DIR(1:NCHAR)//'/'//FNO40
      IF(FNO41.NE. '/dev/null') FNO41=DIR(1:NCHAR)//'/'//FNO41
      IF(FNO42.NE. '/dev/null') FNO42=DIR(1:NCHAR)//'/'//FNO42
      IF(FNO43.NE. '/dev/null') FNO43=DIR(1:NCHAR)//'/'//FNO43
      IF(FNO44.NE. '/dev/null') FNO44=DIR(1:NCHAR)//'/'//FNO44
      IF(FNO50.NE. '/dev/null') FNO50=DIR(1:NCHAR)//'/'//FNO50
      IF(FNO51.NE. '/dev/null') FNO51=DIR(1:NCHAR)//'/'//FNO51
      IF(FNO57.NE. '/dev/null') FNO57=DIR(1:NCHAR)//'/'//FNO57
      IF(FNO80.NE. '/dev/null') FNO80=DIR(1:NCHAR)//'/'//FNO80
      IF(FNO81.NE. '/dev/null') FNO81=DIR(1:NCHAR)//'/'//FNO81
      IF(FNOPT.NE. '/dev/null') FNOPT=DIR(1:NCHAR)//'/'//FNOPT
      OPEN(IIN1,  FILE=FNI1,STATUS='OLD')
      OPEN(IIN2,  FILE=FNI2,STATUS='OLD')
      OPEN(IIN3,  FILE=FNI3,STATUS='OLD')
      OPEN(IIN4,  FILE=FNI4,STATUS='OLD')
      OPEN(IIN5,  FILE=FNI5,STATUS='OLD')
      OPEN(IIN6,  FILE=FNI6,STATUS='OLD')
      OPEN(IIN7,  FILE=FNI7,STATUS='OLD')
      OPEN(IIN8,  FILE=FNI8,STATUS='OLD')
      OPEN(IIN9,  FILE=FNI9,STATUS='OLD')
      OPEN(IIN10,FILE=FNI10,STATUS='OLD')
      OPEN(IIN11,FILE=FNI11,STATUS='OLD')
      OPEN(IIN16,FILE=FNI16,STATUS='OLD')
      OPEN(IIN17,FILE=FNI17,STATUS='OLD')
      OPEN(IIN18,FILE=FNI18,STATUS='OLD')
      OPEN(IIN20,FILE=FNI20,STATUS='OLD')
      OPEN(IIN21,FILE=FNI21,STATUS='OLD')
      OPEN(IIN22,FILE=FNI22,STATUS='OLD')
      OPEN(IIN23,FILE=FNI23,STATUS='OLD')
      OPEN(IIN25,FILE=FNI25,STATUS='OLD')
      OPEN(IIN26,FILE=FNI26,STATUS='OLD')
      OPEN(IIN27,FILE=FNI27,STATUS='OLD')
      OPEN(IIN28,FILE=FNI28,STATUS='OLD')
      OPEN(IIN29,FILE=FNI29,STATUS='OLD')
      OPEN(IIN30,FILE=FNI30,STATUS='OLD')
      OPEN(IIN31,FILE=FNI31,STATUS='OLD')
      OPEN(IIN32,FILE=FNI32,STATUS='OLD')
      OPEN(IIN33,FILE=FNI33,STATUS='OLD')
      OPEN(IIN34,FILE=FNI34,STATUS='OLD')
      OPEN(IIN35,FILE=FNI35,STATUS='OLD')
      OPEN(IIN36,FILE=FNI36,STATUS='OLD')
      OPEN(IIN37,FILE=FNI37,STATUS='OLD')
      OPEN(IIN38,FILE=FNI38,STATUS='OLD')
      OPEN(IIN39,FILE=FNI39,STATUS='OLD')
      OPEN(IIN50,FILE=FNI50,STATUS='OLD')
      OPEN(IIN51,FILE=FNI51,STATUS='OLD')
      OPEN(IIN60,FILE=FNI60,STATUS='OLD')
      OPEN(IIN61,FILE=FNI61,STATUS='OLD')
      OPEN(IIN62,FILE=FNI62,STATUS='OLD')
      OPEN(IIN63,FILE=FNI63,STATUS='OLD')
      OPEN(IIN64,FILE=FNI64,STATUS='OLD')      
      OPEN(IOUT1, FILE=FNO1,STATUS='UNKNOWN')
      OPEN(IOUT2, FILE=FNO2,STATUS='UNKNOWN')
      OPEN(IOUT3, FILE=FNO3,STATUS='UNKNOWN')
      OPEN(IOUT4, FILE=FNO4,STATUS='UNKNOWN')
      OPEN(IOUT5, FILE=FNO5,STATUS='UNKNOWN')
      OPEN(IOUT6, FILE=FNO6,STATUS='UNKNOWN')
      OPEN(IOUT7, FILE=FNO7,STATUS='UNKNOWN')
      OPEN(IOUT8, FILE=FNO8,STATUS='UNKNOWN')
      OPEN(IOUT9, FILE=FNO9,STATUS='UNKNOWN')
      OPEN(IOUT10,FILE=FNO10,STATUS='UNKNOWN')
      OPEN(IOUT11,FILE=FNO11,STATUS='UNKNOWN')
      OPEN(IOUT12,FILE=FNO12,STATUS='UNKNOWN')
      OPEN(IOUT13,FILE=FNO13,STATUS='UNKNOWN')
      OPEN(IOUT14,FILE=FNO14,STATUS='UNKNOWN')
      OPEN(IOUT15,FILE=FNO15,STATUS='UNKNOWN')
      OPEN(IOUT16,FILE=FNO16,STATUS='UNKNOWN')
      OPEN(IOUT17,FILE=FNO17,STATUS='UNKNOWN')
      OPEN(IOUT18,FILE=FNO18,STATUS='UNKNOWN')
      OPEN(IOUT19,FILE=FNO19,STATUS='UNKNOWN')
      OPEN(IOUT20,FILE=FNO20,STATUS='UNKNOWN')
      OPEN(IOUT30,FILE=FNO30,STATUS='UNKNOWN')
      OPEN(IOUT31,FILE=FNO31,STATUS='UNKNOWN')
      OPEN(IOUT32,FILE=FNO32,STATUS='UNKNOWN')
      OPEN(IOUT36,FILE=FNO36,STATUS='UNKNOWN')
      OPEN(IOUT40,FILE=FNO40,STATUS='UNKNOWN')
      OPEN(IOUT41,FILE=FNO41,STATUS='UNKNOWN')
      OPEN(IOUT42,FILE=FNO42,STATUS='UNKNOWN')
      OPEN(IOUT43,FILE=FNO43,STATUS='UNKNOWN')
      OPEN(IOUT44,FILE=FNO44,STATUS='UNKNOWN')
      OPEN(IOUT50,FILE=FNO50,STATUS='UNKNOWN')
      OPEN(IOUT51,FILE=FNO51,STATUS='UNKNOWN')
      OPEN(IOUT57,FILE=FNO57,STATUS='UNKNOWN')
      OPEN(IOUT80,FILE=FNO80,STATUS='UNKNOWN')
      OPEN(IOUT81,FILE=FNO81,STATUS='UNKNOWN')
      OPEN(IOUTPT,FILE=FNOPT,STATUS='UNKNOWN')
C
C  if ITERM=6 terminal output is assumed; otherwise unit ITERM output
C  is to a file
C
      IF (ITERM .NE. 6) THEN
         READ(IFN,*) FNTERM
         OPEN(ITERM,FILE=FNTERM,STATUS='UNKNOWN')
      END IF
C
      
      RETURN
      END
