C
C**************************  INIT_SURF ***********************************
C
C  INITIALIZATION FOR SURFACE ROUTING MODULE FOR THE NO-COUPLING CASE
C
C*************************************************************************
C
      SUBROUTINE INIT_SURF(NCELNL,NUMRES,DELTA_X,DELTA_Y,HSPEFF,
     1     HTIEFF,NSTEP,TIME,DELTAT,DELTATS,QOI_SN,EFFTIM,
     2     SURFACE_WATER_INP)
C
      IMPLICIT NONE
      INCLUDE 'CATHY.H'
      INTEGER NCELNL,NUMRES
      INTEGER HSPEFF,HTIEFF
      INTEGER NSTEP
      REAL*8  DELTA_X,DELTA_Y
      REAL*8  TIME,DELTAT,DELTATS
      INTEGER QOI_SN(*)
      REAL*8  EFFTIM(*),SURFACE_WATER_INP(2,*)
      INCLUDE 'SURFWATER.H'
C
      DELTATS=DELTAT
      NSTEP=1
      CALL INIT0R(MAXCEL,Q_IN_KK_SN)
      CALL INIT0R(MAXCEL,Q_IN_KKP1_SN)
      CALL INIT0R(MAXCEL,Q_OUT_KK_SN_1)
      CALL INIT0R(MAXCEL,Q_OUT_KK_SN_2)
      CALL INIT0R(MAXCEL,Q_OUT_KKP1_SN_1)
      CALL INIT0R(MAXCEL,Q_OUT_KKP1_SN_2)
C
cms   The initialization  of variables in presence of reservoirs needs
cms   to be double-checked
      CALL INIT0R(NUMRES,H_POOL_KK_VEC)
      CALL INIT0R(NUMRES,H_POOL_KK_VEC_P)
      CALL EFFONE(NCELNL,HSPEFF,HTIEFF,DELTA_X,DELTA_Y,TIME,EFFTIM,
     1     QOI_SN,SURFACE_WATER_INP,SURFACE_WATER_SN)
C
      RETURN
      END
