name: pyCATHY_doc
channels:
- conda-forge
- default
dependencies:
- python=3.10
- git
- pip
- pip:
  - numpy
  - numpydoc
  - docutils
  - sphinx
  - sphinx-book-theme #==0.2.*
  - sphinx-gallery #==0.10.*
  - sphinx-design #==0.2.*
  - sphinx-copybutton #==0.5.*
  - sphinx-thebe
  - jupyter-sphinx #==0.3.*
  - sphinxcontrib-bibtex
  - matplotlib
  - pyvista
  - vtk
  - myst_nb
