name: pyCATHY_doc
channels:
- conda-forge
- default
dependencies:
- python=3.10
- git
- pip  # Important to include pip if you want to install pip packages
- pip:
    - -r requirements_doc.txt  # reference to your pip file (optional, see alternative below)