# This is a basic workflow to publish pyCATHY doc

name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_book_theme
          pip install -r env/requirements_doc.txt
          pip install .
          python -m ipykernel install --user --name pyCATHY
      - name: Sphinx build
        run: |
          rm -rf doc/_build/
          sphinx-build doc doc/_build
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/
          force_orphan: true
